name: Lucas Estienne
markdown: kramdown
permalink: /notes/:categories/:year/:month/:title
url: https://lstn.github.io
_my_email: lucas@estienne.sh
_my_name: Lucas Estienne
_my_gh_url: https://github.com/lstn
_my_linkedin_url: https://www.linkedin.com/in/lucas-estienne/

sass:
  sass_dir: _sass
  style: :compressed