name: Lucas Estienne
title: my stuff
window_title: Lucas Estienne's stuff
markdown: kramdown
permalink: /notes/:categories/:year/:month/:title
url: https://lstn.github.io
paginate: 1
baseurl: ""

kramdown:
    footnote_backlink: "&#10548;"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank

_my:
  email: lucas+from_personal_site@limaecho.ca
  name: Lucas Estienne
  gh_url: https://github.com/lstn
  linkedin_url: https://www.linkedin.com/in/lucas-estienne/

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Lucas Estienne
  #url: https://twitter.com/
  email: lucas@limaecho.ca